export const Users = [
    {
      id:1,
      profilePicture: "./assets/person/1.png",
      username: "Mario",
    },
    {
      id:2,
      profilePicture: "./assets/person/2.png",
      username: "Kirby",
    },
    {
      id:3,
      profilePicture: "./assets/person/3.png",
      username: "Princess Zelda",
    },
    {
      id:4,
      profilePicture: "./assets/person/4.png",
      username: "Wario",
    },
    {
      id:5,
      profilePicture: "./assets/person/5.png",
      username: "Donkey Kong",
    },
    {
      id:6,
      profilePicture: "./assets/person/6.png",
      username: "Yoshi",
    },
    {
      id:7,
      profilePicture: "./assets/person/7.png",
      username: "Toad",
    },
    {
      id:8,
      profilePicture: "./assets/person/8.png",
      username: "Link",
    },
    {
      id:9,
      profilePicture: "./assets/person/9.png",
      username: "Luigi",
    },
    {
      id:10,
      profilePicture: "./assets/person/10.png",
      username: "Bowser",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      title: "Where you at?",
      desc: "HMU if you are in Tunalı!",
      photo: "./assets/post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      title: "Welcome to the beach!",
      photo: "./assets/post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 0,
      comment: 1,
    },
    {
      id: 3,
      desc: "Why would someone go to Bahçeli lol :D",
      photo: "./assets/post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "./assets/post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "./assets/post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "./assets/post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "I hate summers dude",
      photo: "./assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "./assets/post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Ankara",
      photo: "./assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Trying to not have a breakdown while having to code & design the front-end part of the project all by myself",
      photo: "./assets/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 999,
      comment: 12,
    },
  ];